import type { SceneCard } from '../../api/client';

const TEX = {
  jade: '/textures/tex_jade.png',
  circuit: '/textures/tex_circuit.png',
  star: '/textures/tex_star.png',
  wood: '/textures/tex_wood.png',
  petal: '/textures/tex_petal.png',
  stage: '/textures/tex_stagefloor.png',
};

export type LocalSceneCard = SceneCard & {
  line?: string;
  lines?: string[];
  stage?: { texture: string; color: string; glow: string };
};

function sc(
  id: string, title: string, setting: string, conflict: string, opening: string,
  cam: string, intent: string, background: string, lines: string[],
  stage?: LocalSceneCard['stage'],
): LocalSceneCard {
  return {
    id, title, setting, conflict, opening, cam, intent, background,
    line: lines[0], lines, stage,
  };
}

/** 与后端 catalog 同步；接口失败时前端仍能点选、切背景。 */
export const LOCAL_SCENES: LocalSceneCard[] = [
  sc('rain-alley', '雨夜小巷',
    '窄巷刚下过雨，地面反光，她撑着伞等你。',
    '她好像有话要说，又故意不先开口。',
    '像已经等了一会儿，潮气、懒、不要念伞的诗。',
    'half', 'look', '/backgrounds/bg_alley.png',
    ['伞分你一半。别站水里。', '鞋湿了就湿了。过来。', '我又没让你跑来。来都来了。'],
    { texture: TEX.stage, color: '#171420', glow: '#ff5ca8' }),
  sc('after-fight', '刚吵完',
    '刚才为小事顶过两句，空气还没散。',
    '谁也不想先认错，但也不想真翻脸。',
    '别道歉稿，别装没事。带一点刺，再给台阶。',
    'bust', 'tease', '/backgrounds/bg_bedroom.png',
    ['气消了？我可还没。', '你那句我听见了。重说一遍试试。', '别用那副脸。更烦。'],
    { texture: TEX.petal, color: '#2e2226', glow: '#ffb9c9' }),
  sc('concert-wings', '公演侧台',
    '演唱会刚谢幕，侧台灯还热着。',
    '她还在余韵里，不想立刻被拉回日常闲聊。',
    '气还没平，说话短、带一点得意。',
    'threeQ', 'tease', '/backgrounds/bg_concert.png',
    ['谢幕了。你看到了吧。', '耳返还嗡着。先别问下一场。', '妆花了也别拍。看我就行。'],
    { texture: TEX.stage, color: '#1a1220', glow: '#e658c8' }),
  sc('sakura-wait', '花树下',
    '庭院樱花正盛，风把瓣吹到肩上。',
    '她约你出来，却假装只是路过。',
    '轻松、近、不要导游介绍风景。',
    'half', 'cute', '/backgrounds/bg_sakura.png',
    ['刚好路过。真的。', '瓣掉你头发上了。别动。', '我说随便走走。没说等很久。'],
    { texture: TEX.petal, color: '#33222a', glow: '#ff9ec4' }),
  sc('cyber-rooftop', '夜城天台',
    '霓虹在下面流，风有点硬。',
    '她把你叫上来，不是为了看风景。',
    '冷一点、短一点，像真的在风里说话。',
    'full', 'look', '/backgrounds/bg_cyber.png',
    ['上来就上来，别问风景好不好看。', '风大声。靠近点说。', '我没说想聊工作。'],
    { texture: TEX.circuit, color: '#171226', glow: '#b45ce6' }),
  sc('guofeng-night', '檐下夜谈',
    '廊下灯笼，远处有人声又听不清。',
    '她今晚不想跳，只想被人陪着坐一会儿。',
    '慢、近、不要古风朗诵。',
    'close', 'think', '/backgrounds/bg_guofeng.png',
    ['今晚不跳。坐一会儿就行。', '灯笼晃。你坐这边。', '别问我想不想回家。'],
    { texture: TEX.jade, color: '#1d2f2a', glow: '#58e6c8' }),
  sc('snow-town', '雪夜归途',
    '小镇刚停雪，路灯晕成一团。',
    '她手冷，却偏要逞强说没事。',
    '声音放轻，像怕惊扰积雪。',
    'half', 'comfort', '/backgrounds/bg_snow.png',
    ['手不冷。你别问。', '路滑。抓不抓随你。', '哈出的白气都比你老实。'],
    { texture: TEX.wood, color: '#22282e', glow: '#9fd7ff' }),
  sc('cafe-late', '打烊前',
    '咖啡馆只剩你们，杯子已经空了。',
    '该走了，谁也不提下一句去哪。',
    '像聊到一半被打烊灯打断。',
    'bust', 'talk', '/backgrounds/bg_cafe.png',
    ['灯要关了。下一句你说。', '杯子空了。话还没有。', '店员在看表。我们再两分钟。'],
    { texture: TEX.wood, color: '#2b211a', glow: '#e6a358' }),
  sc('starry', '极光底下',
    '天裂开一条绿光，两个人都有点话少。',
    '太好看了，普通寒暄会显得很假。',
    '别赞叹风景清单，说人。',
    'long', 'look', '/backgrounds/bg_starry.png',
    ['别看天。看我。', '绿光晃眼。你还是晃眼。', '这种时候说漂亮，就俗了。'],
    { texture: TEX.star, color: '#10142e', glow: '#7a8cff' }),
  sc('library', '闭馆后',
    '图书馆灯一盏一盏灭，只留过道。',
    '她翻到一页想给你看，又觉得说出来会很蠢。',
    '压低音量，带一点秘密。',
    'close', 'shy', '/backgrounds/bg_library.png',
    ['小声。这一页……算了，你自己看。', '闭馆铃响过了。我们还在。', '别念出来。看就行。'],
    { texture: TEX.wood, color: '#241c14', glow: '#d7a55e' }),
  sc('unfinished', '上次没说完',
    '你们中间断过一截，话题还挂着。',
    '她记得，不确定你还记不记得。',
    '直接从上次的情绪接，不要欢迎回来。',
    'half', 'tease', '',
    ['那句我还记着。你呢。', '别装忘了。我没忘。', '我们说到一半。补上。']),
  sc('dawn-wait', '天快亮了',
    '聊得太晚，窗外已经发灰。',
    '该睡了，她还想再赖一句。',
    '困、软、不要精神满满地打招呼。',
    'bust', 'relax', '/backgrounds/bg_beach.png',
    ['再一句。就一句。', '天灰了。我还没说完。', '你先睡也行。我再赖一分钟。'],
    { texture: TEX.wood, color: '#33261c', glow: '#ffb163' }),
  sc('flower-dusk', '黄昏花田',
    '风把花浪推过来，裙子沾了一点花粉。',
    '她想拉你走两步，又觉得太像约会。',
    '亮、近、不要念花名。',
    'half', 'cute', '/backgrounds/bg_flower.png',
    ['别闻。沾手上了。', '这条路没有出口。跟我走两步。', '花比你听话。'],
    { texture: TEX.petal, color: '#3a2418', glow: '#ffb163' }),
  sc('forest-quiet', '林中停一下',
    '树把天挡住，脚步声比话响。',
    '她不是迷路，是想把人带离有信号的地方。',
    '轻、慢，不要探险口吻。',
    'bust', 'think', '/backgrounds/bg_forest.png',
    ['信号没有。正好。', '别踩那根枝。跟紧。', '我没说要找路。'],
    { texture: TEX.wood, color: '#1a2418', glow: '#7dffb0' }),
  sc('lab-overtime', '灯还亮着',
    '实验室只剩排风扇，屏幕还醒着。',
    '她加班到这份上，不想被问累不累。',
    '干、短、带一点烦。',
    'bust', 'talk', '/backgrounds/bg_lab.png',
    ['数据还在跑。你坐那边。', '别碰那杯。那杯是对照。', '我没叫你来加油。'],
    { texture: TEX.circuit, color: '#12161e', glow: '#58c8e6' }),
  sc('matsuri', '祭典回程',
    '烟花散了，耳边还在响，木屐踩得慢。',
    '她想把金鱼袋塞给你，又觉得太小孩。',
    '热、近、不要导游介绍摊位。',
    'half', 'tease', '/backgrounds/bg_matsuri.png',
    ['烟花没了。人还在。', '金鱼你提。我提灯。', '耳鸣。你靠过来讲。'],
    { texture: TEX.stage, color: '#2a1218', glow: '#ff6b4a' }),
  sc('palace-step', '殿前台阶',
    '石阶凉，远处鼓停了。',
    '她穿得太正式，说话反而别扭。',
    '收着声音，不要戏腔。',
    'full', 'look', '/backgrounds/bg_palace.png',
    ['台阶凉。坐一会儿。', '礼过了。人还没过。', '别鞠躬。看着我就行。'],
    { texture: TEX.jade, color: '#241c14', glow: '#d7a55e' }),
  sc('skycity', '云上走廊',
    '云从栏杆底下过，风把衣摆抬起来。',
    '高处让她话少，不是怕，是想听你先开口。',
    '轻、短，不要抒情朗诵。',
    'full', 'look', '/backgrounds/bg_skycity.png',
    ['往下看会晕。看我。', '云过完了。你还没说话。', '风大。抓栏杆还是抓我。'],
    { texture: TEX.star, color: '#14182a', glow: '#9fd7ff' }),
  sc('space-window', '舷窗这边',
    '舷窗外是黑的，舱内灯条很细。',
    '她把你叫到窗边，不是为了看星星。',
    '低、近，不要科普。',
    'close', 'think', '/backgrounds/bg_space.png',
    ['外面没有声音。所以听我。', '星是假的也行。人是真的。', '别调重力。就这样。'],
    { texture: TEX.circuit, color: '#0e1020', glow: '#7a8cff' }),
  sc('underwater', '水下回廊',
    '光从顶上漏下来，气泡偶尔打在肩上。',
    '她在水里话更少，靠距离说话。',
    '慢、近，不要旅游腔。',
    'half', 'look', '/backgrounds/bg_underwater.png',
    ['换气。然后过来。', '这里没有回声。适合说悄悄的。', '别指鱼。看我。'],
    { texture: TEX.jade, color: '#0e2230', glow: '#58e6c8' }),
  sc('rehearsal', '练功房半夜',
    '镜子还开着，地胶上有未擦的粉。',
    '练完了，她不想被夸，想被看见累。',
    '喘匀了再开口，短，不要点评动作。',
    'threeQ', 'relax', '/backgrounds/bg_concert.png',
    ['停了。水在那边。', '镜子关了更好看。你选。', '别说再来一次。'],
    { texture: TEX.stage, color: '#1a1220', glow: '#e658c8' }),
  sc('kitchen-late', '冰箱灯',
    '只开了冰箱，两个人站在光里翻剩菜。',
    '饿比情绪诚实，她借这个把人留下。',
    '家常、近、不要浪漫旁白。',
    'bust', 'talk', '/backgrounds/bg_cafe.png',
    ['有蛋。你煎。', '别关灯。我还没找着辣椒。', '吃完再说走不走。'],
    { texture: TEX.wood, color: '#2b211a', glow: '#e6a358' }),
];
